config/routes.rb
  get 'placements/interview_rounds_new'=>'placements#interview_rounds_new',as: :interview_rounds_new
  get 'placements/:id/interview_rounds_edit'=>'placements#interview_rounds_edit',as: :interview_rounds_edit
  post 'placements/interview_rounds_create'=>'placements#interview_rounds_create',as: :interview_rounds_create
  patch 'placements/:id/interview_rounds_update'=>'placements#interview_rounds_update',as: :interview_rounds_update
  get 'placements/:id/interview_rounds_delete'=>'placements#interview_rounds_delete',as: :interview_rounds_delete
  get 'placements/:id/interview_rounds_show'=>'placements#interview_rounds_show',as: :interview_rounds_show


    get 'placements/corporate_profile_update'=>'placements#corporate_profile_update',as: :corporate_profile_update
#jayanth
    get 'placements/corporate_profile_edit/:id'=>'placements#corporate_profile_edit',as: :corporate_profile_edit

        get 'placements/:id/training_offered_list'=>'placements#training_offered_list',as: :training_offered_list

    get 'placements/corporate_profile'=>'placements#corporate_profile',as: :corporate_profile

    get 'placements/placement_training_offered_list'=>'placements#placement_training_offered_list',as: :placement_training_offered_list


    get 'placements/placement_training_offered_accept'=>'placements#placement_training_offered_accept',as: :placement_training_offered_accept
    get 'placements/filter_company_data_training'=>'placements#filter_company_data_training',as: :filter_company_data_training

    get 'training_offered'=>'placements#training_offered',as: :training_offered
    get 'placements#training_offered_new'=>'placements#training_offered_new',as: :training_offered_new
    get 'placements/training_offered_create'=>'placements#training_offered_create',as: :training_offered_create
    get 'placements/:id/training_offered_edit'=>'placements#training_offered_edit',as: :training_offered_edit
    get 'placements/training_offered_update'=>'placements#training_offered_update',as: :training_offered_update
    get 'placements/:id/training_offered_delete'=>'placements#training_offered_delete',as: :training_offered_delete
    get 'placements/:id/training_offered_show'=>'placements#training_offered_show',as: :training_offered_show
    get 'placements/training_offered_validation'
   
    get 'placements/job_apply'=>'placements#job_apply',as: :job_apply
    get 'placements/job_apply_new'=>'placements#job_apply_new',as: :job_apply_new
    get 'placements/job_apply_create'=>'placements#job_apply_create',as: :job_apply_create
    get 'placements/job_apply_update'=>'placements#job_apply_update',as: :job_apply_update
    get 'placements/:id/job_apply_edit'=>'placements#job_apply_edit',as: :job_apply_edit
    get 'placements/:id/job_apply_show'=>'placements#job_apply_show',as: :job_apply_show
    get 'placements/:id/job_apply_delete'=>'placements#job_apply_delete',as: :job_apply_delete
    get 'placements/onchange_data'=>'placements#onchange_data',as: :onchange_data
    get 'placements/readonly_data'=>'placements#readonly_data',as: :readonly_data
    get 'placements/onchange_data_edit'=>'placements#onchange_data_edit',as: :onchange_data_edit
    get 'placements/select_data_based_on_semester_graph_data'=>'placements#select_data_based_on_semester_graph_data',as: :select_data_based_on_semester_graph_data

      #get 'placements/placement_report'

    get 'placements/send_notification'=>'placements#send_notification',as: :send_notification
    get 'placements/placement_student_selection'=>'placements#placement_student_selection',as: :placement_student_selection
    get 'placements/:id/placement_student_selection_edit'=>'placements#placement_student_selection_edit',as: :placement_student_selection_edit
    get 'placements/placement_student_selection_create'=>'placements#placement_student_selection_create',as: :placement_student_selection_create

      get 'placements/student_status_report'
      get 'placements/placement_report'
      get 'placements/select_data_based_on_semester_graph'
      
      get 'placements/select_data_based_on_semester'
      get 'placements/:id/placement_student_selection_show'=>'placements#placement_student_selection_show',as: :placement_student_selection_show
      get 'placements/interview_status_for_student'
      get 'placements/student_selection'
      get 'placements/student_selection_new'
      get 'placements/select_students_on_job'
      get 'placements/select_students_on_job_edit'
      get 'placements/student_selection_create'=>'placements#student_selection_create',as: :student_selection_create
      get 'placements/:id/student_selection_show'=>'placements#student_selection_show',as: :student_selection_show
      get 'placements/:id/student_selection_edit'=>'placements#student_selection_edit',as: :student_selection_edit
      get 'placements/:id/student_selection_delete'=>'placements#student_selection_delete',as: :student_selection_delete
      get 'placements/student_selection_update'=>'placements#student_selection_update',as: :student_selection_update
      get 'placements/interview_status'=>'placements#interview_status',as: :interview_status


# balaji's
    get 'placements/job_upload'=>"placements#job_upload"
    get 'placements/job_upload_new'=>'placements#job_upload_new'
    get 'placements/job_upload_create'=>'placements#job_upload_create'
    get 'placements/:id/job_upload_show'=>"placements#job_upload_show"
    patch 'placements/:id/job_upload_update'=>"placements#job_upload_update"
    get 'placements/job_upload_accept'=>'placements#job_upload_accept'
    get 'placements/:id/training_request_accept'=>"placements#training_request_accept"
    get 'placements/:id/job_upload_reject'=>"placements#job_upload_reject"
    get 'placements/filter_company_data'=>"placements#filter_company_data"
    get 'placements/placement_training_requested_show'=>"placements#placement_training_requested_show"
    get 'placements/:id/job_upload_show_student'=>"placements#job_upload_show_student"

    get 'placements/:id/placement_training_requested_show'=>"placements#placement_training_requested_show"
    get 'placements/placement_training_status_update'=>"placements#placement_training_status_update"
    
    get 'placements/:id/job_upload_show_student'=>"placements#job_upload_show_student"

    get 'placements/:id/student_doc_edit'=>'placements#student_doc_edit'
    
      get 'placements/index'

    
 get 'placements/placement_student_detail_index'=>'placements#placement_student_detail_index',as: :placement_student_detail_index
  get 'placements/placement_student_detail_new'=>'placements#placement_student_detail_new',as: :placement_student_detail_new
  post 'placements/placement_student_detail_create'=>'placements#placement_student_detail_create',as: :placement_student_detail_create
  get 'placements/placement_student_detail_edit/:id'=>'placements#placement_student_detail_edit',as: :placement_student_detail_edit
  patch 'placements/:id/placement_student_detail_update'=>'placements#placement_student_detail_update',as: :placement_student_detail_update
  delete 'placements/placement_student_detail_delete/:id'=>'placements#placement_student_detail_delete',as: :placement_student_detail_delete
  get 'placements/placement_student_detail_show/:id'=>'placements#placement_student_detail_show',as: :placement_student_detail_show
  
  get 'placements/student_uploaded_resume_index'=>'placements#student_uploaded_resume_index',as: :student_uploaded_resume_index
  get 'placements/student_resume_upload_new'=>'placements#student_resume_upload_new',as: :student_resume_upload_new
  post 'placements/student_resume_upload_create'=>'placements#student_resume_upload_create',as: :student_resume_upload_create
  get 'placements/change_default_resume/:id'=>'placements#change_default_resume',as: :change_default_resume
  delete 'placements/delete_student_resume/:id'=>'placements#delete_student_resume',as: :delete_student_resume
  get 'placements/student_resume_upload_show/:id'=>'placements#student_resume_upload_show',as: :student_resume_upload_show
 
  get 'placements/index_corporate_login'=>'placements#index_corporate_login',as: :index_corporate_login
  get 'placements/index_placement_cell_head'=>'placements#index_placement_cell_head',as: :index_placement_cell_head
  get 'placements/index_recruitment_assistant'=>'placements#index_recruitment_assistant',as: :index_recruitment_assistant
  get 'placements/new_user'=>'placements#new_user',as: :new_user
  post 'placements/create_user'=>'placements#create_user',as: :create_user
  get 'placements/edit_user/:id'=>'placements#edit_user',as: :edit_user
  patch 'placements/:id/update_user'=>'placements#update_user',as: :update_user
  delete 'placements/delete_user/:id'=>'placements#delete_user',as: :delete_user
  get 'placements/change_password/:id'=>'placements#change_password',as: :corporate_change_password
  get 'placements/user_change_password'=>'placements#user_change_password',as: :user_change_password
  # Added by Bindhu for Login Cr














get 'sessions/database_details'
get 'sessions/login_details'

  get 'alumni/video_gallery_list'=>'alumni#video_gallery_list',as: :video_gallery_list
  get 'alumni/photo_gallery_list'=>'alumni#photo_gallery_list',as: :photo_gallery_list
  get 'alumni/gallery_list'=>'alumni#gallery_list',as: :gallery_list
  

  get 'alumni/online_store' => 'alumni#online_store'
  get 'alumni/online_store_item_list'=>"alumni#online_store_item_list"
  get 'alumni/online_store_item_show'=>"alumni#online_store_item_show"
  post 'alumni/cart_update'=>'alumni#cart_update',as: :cart_update
  get 'alumni/online_store_cart_show'=>'alumni#online_store_cart_show'
  get 'alumni/online_store_item_buy_from_cart'=>'alumni#online_store_item_buy_from_cart'
  get 'alumni/online_store_history'=>'alumni#online_store_history'
  get 'alumni/alumni_search'


  get 'alumni/payment_new'
  get 'alumni/payment_create'
  get 'alumni/payment_show'
  get 'alumni/payment_edit'

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification_left.html.erb
<!--   s Sec --> <section id="userBodyContentBox" style="margin: 0 auto;">
    <table  border="0" cellspacing="0" cellpadding="0"  style="margin-bottom: 0px;">
        <tr>
            <td valign="top" class="userBodyContentBox1">
                <aside class="userMenuBoxLeft" style="width: 210px;">
                    <ul class="menuListHome">
                     <li class="myAccountMenu">Notifications</li>
                       
                        <li id="viewPrincipleNotificationLiID">

                            <a class="Principle-Profile" href="/notifications" id="viewPrincipleNotification">
                                <div class="setMenu"><i class="fa fa-comment">&nbsp;&nbsp;</i>Send Notification
                                </div>
                            </a>
                        </li>

                        
                        <li id="showAdminNotificationLiID">

                            <a class="Principle-Profile" href="/notifications/show_by_box" id="showAdminNotification">
                                <div class="setMenu"><i class="fa fa-weixin">&nbsp;&nbsp;</i>Show Notification
                                </div>
                            </a>
                        </li>


                        

                    </ul>    

                </aside>
            </td>
            <td  valign="top" id="manageEmployeeCategoryID" class="mg-table-td-main-2" style="width: 745px;">
            
<script>
$( document ).ready(function() {
    
    focusNotification();
});
</script>

app/views/notifications/_notification_left_close.html.erb
<!--s Sec -->           </td>
        </tr>
    </table>
</section>
<br/>

app/views/notifications/_show_notify.html.erb
<h4 class="mg-h4" style="width: 736px;"><%=t('notifications')%></h4>
	<% if @notifications.length > 0 %>
	<div class="mg_pagination">
	<div class="container mg-btn-bottom-margin" style="width: 736px; margin-left: -15px;">
	<!-- 	s<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#showNotificationPage">Notifications <span class="badge"><%#= @size %></span></button> -->
	      <div id="showNotificationPage2" class="collapse-sh">

	     
	     	<div class="notification-list" style="width:736px">
	     		
	     	
		        <%  @notifications.each do |notification| %>
				
               <a href="/notifications/view_notification/<%= notification.id %>" class="anchor-btn mg-rm-pagination-style" >
						<% if notification.status %>
							<div class="notification notification-seen">
						<% else %>
							<div class="notification notification-unseen">
						<% end %>
						
							<div class="notification-label">
								<%= notification.subject %>
							</div>
							<div class="notification-data mg-file-clr">
								<%=truncate(notification.description.to_s, :length => 75, :separator => ' ') %>
							</div>
						</div>
                </a>
		          	 
		        <% end %>
	        </div>
	      
	      </div>
	</div>
	<p>
	<%= will_paginate @notifications, :container => false %>
	</p>
  </div>
	<% else %>
	<h5 class="mg-custom-labels">No notification...</h5>
	<% end %>

app/views/notifications/_view_notify.html.erb
<h4 class="mg-h4"><%=t('view notification')%></h4>
	<div class="container" style="width: 736px; margin-left: -14px;">
	<p>
		<label class="mg-label mg-leave-width">Subject </label> 
		<label class="mg-label-inner-form"><%= @notification.subject %> 
		<% @user = MgUser.find(@notification.from_user_id) %></label>
	</p>
	<p>
		<label class="mg-label mg-leave-width">From </label> 
		<%if session[:user_type]=="central_account_incharge"%>
			<label class="mg-label-inner-form"><%= @user.user_name %></label>
		<%else%>
			<label class="mg-label-inner-form"><%= @user.first_name %></label>
		<%end%>
	</p> 
	<p>
		<label class="mg-label mg-leave-width">Description </label>
		<label class="mg-label-inner-form"><%= @notification.description %> </label>
	</p>


	<%#= @notsification.inspect %>
    <div class="row">
     <div class="col-md-6">
		<span class="mg-button-align" style="margin-right: 3px;">
			<% if @notification.status %>
				<%if((@parent_url!=nil) && (@parent_url.include? "show_by_box")) %>
					<%= button_to "Mark as Unseen", principal_notification_unseen_path(@notification.id), :class => "mg-small-form-btn ",:method => :get %>
				<% else %>
					<%= button_to "Mark as Unseen", notification_unseen_path(@notification.id), :class => "mg-small-form-btn ",:method => :get %>
				<% end %>			    
			       
			<% else %>
					
					 <%#= button_to "Mark as Seen", notification_seen_path(@notification.id), :class => "mg-small-form-btn ",:method => :get %>
			<% end %>&nbsp;
		</span>
		<span class="mg-button-align" style="position: relative; top:0px;">
		<%= button_to "Back", show_notification_path, :class => "mg-small-form-btn",:method => :get %>
		<%#= link_to t('back'), :back, {:class=>"mg-small-form-btn cancel-form-dialog"} %>
		</span>

	</div>

	</div>

</div>

app/views/notifications/index.html.erb
<!-- jyhasgd-->
<% navigation_add t('send_notification'), notifications_path %>
<%= render  partial: 'notification_left' %>
<%user=MgUser.find(session[:user_id])%>
<%=hidden_field_tag 'user_type', user.user_type%>

<%= render partial: 'notifications/send_notification' %>

<%= render  partial: 'application/common_left_close' %>

<script type="text/javascript">
     $(document).ready(function(){

     	 focusCurrentTab("viewPrincipleNotification","viewPrincipleNotificationLiID");
     	 // focusNotification();
     	 var user_type=$("#user_type").val();
     	 console.log(user_type);
     	 if(user_type=="superprincipal" || user_type=="principal" || user_type=="admin"){
     	 	focusNotification();
     	 }
     	 else{
     	 	focusDashboards();
     	 }
         
   });
</script>

app/views/notifications/principal_notifications.html.erb
<% navigation_add 'Send Notifications', principal_notifications_path %>

<%user=MgUser.find(session[:user_id])%>
<%=hidden_field_tag 'user_type', user.user_type%>
<!--ss Principle no-->
<% if @user_type.to_s == "employee" %>

	<%#= render partial: 'application/common_left_close' %>
 <%= render partial: '/dashboards/employee_left' %>
    
    <!-- <p>employee</p> -->
    <% if !params[:emailnotice].blank? %>
        <div class="alert alert-info mg-success-msg">
          <%= params[:emailnotice] %>
        </div>
    <% end %>
	<%= render partial: 'notifications/send_notification' %>
		
	<%= render partial: 'application/common_left_close' %>
<%# end %>
<%# elsif @user_type.to_s == "principal" %>

	<%#= render partial: 'dashboards/principle_dashboard_left' %>
	<%#= render partial: 'notifications/send_notification' %>
	<%#= render partial: 'dashboards/principle_dashboard_left_close' %>

<% else @user_type.to_s == "admin" || @user_type.to_s == "principal" || @user_type.to_s == "superprincipal" %>
	<%= render  partial: 'notification_left' %>
    <% if !params[:emailnotice].blank? %>
        <div class="alert alert-info mg-success-msg">
          <%= params[:emailnotice] %>
        </div>
    <% end %>
	<%= render partial: 'notifications/send_notification'  %>

	<%= render  partial: 'application/common_left_close' %>

<% end %>

<script type="text/javascript">
     $(document).ready(function(){

     	 focusCurrentTab("viewPrincipleNotification","viewPrincipleNotificationLiID");
     	 // focusNotification();
     	 var user_type=$("#user_type").val();
     	 console.log(user_type);
     	 if(user_type=="superprincipal" || user_type=="principal"){
     	 	focusNotification();
     	 }
     	 else{
     	 	focusDashboards();
     	 }
         
   });
</script>

app/views/notifications/show_by_box.html.erb
<% navigation_add 'Show Notifications', "/notifications/show_by_box" %>
<%= render  partial: 'notification_left' %>
<%user=MgUser.find(session[:user_id])%>
<%=hidden_field_tag 'user_type', user.user_type%>
<%= render partial: 'show_notify' %>

<%= render  partial: 'application/common_left_close' %>
<script type="text/javascript">
     $(document).ready(function(){
//dd
     	 focusCurrentTab("showAdminNotification","showAdminNotificationLiID");
         var user_type=$("#user_type").val();
     	 if(user_type=="superprincipal" || user_type=="principal" || user_type=="admin"){
     	 	focusNotification();
     	 }
     	 else{

         	focusDashboards();
     	 }
   });
</script>

app/views/notifications/show_notification.html.erb
<!--  sssSec --> 
<% navigation_add 'Show Notifications', show_notification_path %>

<%=hidden_field_tag 'user_type', @user_type%>
<% if @user_type.to_s == "employee" %>

	<%= render partial: 'dashboards/employee_left' %>
    <!-- <p>employee</p> -->
	<%= render partial: 'show_notify' %>
		
	<%= render partial: 'application/common_left_close' %>
<% end %>

<% if @user_type.to_s == "principal" %>

	<%= render partial: 'dashboards/principle_dashboard_left' %>
	<!-- <p>principle</p> -->
	<%= render partial: 'show_notify' %>
		
	<%= render partial: 'application/common_left_close' %>

<% end %>

<% if @user_type.to_s == "student" %>

	<%= render partial: 'dashboards/student_dashboard_left' %>
	<!-- <p>principle</p> -->
	<%= render partial: 'show_notify' %>
		
	<%= render partial: 'application/common_left_close' %>

<% end %>


<% if @user_type.to_s == "guardian" %>

	<%= render partial: 'dashboards/guardian_dashboard_left' %>
	<!-- <p>principle</p> -->
	<%= render partial: 'show_notify' %>
		
	<%= render partial: 'application/common_left_close' %>

<% end %>

<% if @user_type.to_s == "admin" %>

	<%= render partial: 'notification_left' %>
	<!-- <p>principle</p> -->
	<%= render partial: 'show_notify' %>
		
	<%= render partial: 'application/common_left_close' %>

<% end %>

<% if @user_type.to_s == "central_account_incharge" %>

	<%= render partial: 'accounts/accounts_left' %>
	<!-- <p>principle</p> -->
	<%= render partial: 'show_notify' %>
		
	<%= render partial: 'application/common_left_close' %>

<% end %>


<script type="text/javascript">
     $(document).ready(function(){
     	var user_type=$("#user_type").val();
     	 if(user_type=="superprincipal" || user_type=="admin"){
     	 	focusCurrentTab("showAdminNotification","showAdminNotificationLiID");
     	 }
     	 else{
     	 	focusCurrentTab("showPrincipleNotification","showPrincipleNotificationLiID");
     	 }
         	
   });
</script>

app/views/notifications/view_notification.html.erb
<!-- Sec sdzv--> 
<% navigation_add 'Show Notifications', show_notification_path %>
<% navigation_add 'View Notifications', "/notifications/view_notification/#{@notification.id}" %>
<%=hidden_field_tag 'user_type', @user_type%>
<% if @user_type.to_s == "employee" %>

	<%= render partial: 'dashboards/employee_left' %>
    <!-- <p>employee</p> -->
		<%= render partial: 'view_notify' %>
		
	<%= render partial: 'application/common_left_close' %>
<% end %>

<% if @user_type.to_s == "principal" %>
	
	
	<%if((@parent_url!=nil) && (@parent_url.include? "show_by_box")) %>
		<%= render  partial: 'notification_left' %>
	<%else%>
		<%= render partial: 'dashboards/principle_dashboard_left' %>
	<%end%>
	<%= render partial: 'view_notify' %>

	<%= render partial: 'application/common_left_close' %>
<% end %>




<% if @user_type.to_s == "student" %>

	<%= render partial: 'dashboards/student_dashboard_left' %>
	<!-- <p>principle</p> -->
	<%= render partial: 'view_notify' %>
		
	<%= render partial: 'application/common_left_close' %>

<% end %>

<% if @user_type.to_s == "guardian" %>

	<%= render partial: 'dashboards/guardian_dashboard_left' %>
	<!-- <p>principle</p> -->
	<%= render partial: 'view_notify' %>
		
	<%= render partial: 'application/common_left_close' %>

<% end %>

<% if @user_type.to_s == "admin" %>

	<%= render partial: 'notification_left' %>
	<!-- <p>principle</p> -->
	<%= render partial: 'view_notify' %>
		
	<%= render partial: 'application/common_left_close' %>

<% end %>

<% if @user_type.to_s == "central_account_incharge" %>

	<%= render partial: 'accounts/accounts_left' %>
	<%= render partial: 'view_notify' %>
	<%= render partial: 'application/common_left_close' %>

<% end %>


<script type="text/javascript">
     $(document).ready(function(){
     	var user_type=$("#user_type").val();
     	 if(user_type=="superprincipal" || user_type=="admin"){
     	 	focusCurrentTab("showAdminNotification","showAdminNotificationLiID");
     	 }
     	 else{
     	 	focusCurrentTab("showPrincipleNotification","showPrincipleNotificationLiID");
     	 }
   });
</script>