config/routes.rb
  get 'front_office_management/query_record_excel'

  get "front_office_management/category" => "front_office_management#category"
  get "front_office_management/category_new" => "front_office_management#category_new"
  get "front_office_management/category_create" => "front_office_management#category_create"
  get "front_office_management/category_edit" => "front_office_management#category_edit"
  get "front_office_management/category_update" => "front_office_management#category_update"
  get "front_office_management/sub_category" => "front_office_management#sub_category"
  get "front_office_management/sub_category_new" => "front_office_management#sub_category_new"
  get "front_office_management/sub_category_create" => "front_office_management#sub_category_create"
  get "front_office_management/sub_category_edit" => "front_office_management#sub_category_edit"
  get "front_office_management/sub_category_update" => "front_office_management#sub_category_update"

  get "front_office_management/faq" => "front_office_management#faq"
  get "front_office_management/faq_new" => "front_office_management#faq_new"
  get "front_office_management/faq_create" => "front_office_management#faq_create"
  get "front_office_management/faq_edit" => "front_office_management#faq_edit"
  get "front_office_management/faq_update" => "front_office_management#faq_update"
  get "front_office_management/faq_show" => "front_office_management#faq_show"
  get "front_office_management/faq_view" => "front_office_management#faq_view"

  get 'front_office_management/sub_category_list/:id' => 'front_office_management#sub_category_list'
  get 'front_office_management/faq_status'

  get 'front_office_management/meeting'
  get 'front_office_management/meeting_create'
  get 'front_office_management/meeting_new'
  get 'front_office_management/:id/meeting_edit' =>'front_office_management#meeting_edit'
  get 'front_office_management/:id/meeting_show' =>'front_office_management#meeting_show'

  #kumar======ends=================================

  get 'front_office_management/index'
  get 'front_office_management/create'
  get 'front_office_management/update'
  get 'front_office_management/delete'
  get 'front_office_management/show'
  get 'front_office_management/new'
  get 'front_office_management/edit'



get 'exam_management/show_examination_grades'
get 'exam_management/examination_grades'
get 'exam_management/examination_grades_show'
get 'exam_management/examination_grades_add_grades'
get 'exam_management/examination_grades_add_new_grade'
get 'exam_management/examination_grades_edit'
get 'exam_management/examination_grades_update'
get 'exam_management/examination_grades_destroy'



 get 'dashboards/query_record_index_data', as: :query_record_index_data
 get 'dashboards/controller_question_paper'
 get 'dashboards/controller_question_paper_list'
  
 get 'dashboards/employee_question_paper'
  get 'dashboards/employee_question_paper_new'
  post 'dashboards/employee_question_paper_create'=>'dashboards#employee_question_paper_create', as: :question_paper_create
  # post 'dashboards/employee_question_paper_create'
  get 'dashboards/employee_question_paper_show'
  get 'dashboards/employee_question_paper_edit'=>'dashboards#employee_question_paper_edit', as: :question_paper_edit
  get 'dashboards/employee_question_paper_update'




  get 'dashboards/exam_management_select_class'
  get 'dashboards/exam_management_select_section'
  get 'dashboards/exam_management_select_subject'
  get 'dashboards/delete_record_data'
  get 'dashboards/hod_question_paper'
  
  get 'dashboards/employee_question_paper_hod'

  
  get 'dashboards/hod_question_paper_list'
get 'exam_management/exam_fee_category'
 get 'exam_management/exam_fee_category_new'
 get 'exam_management/exam_fee_category_create'
 get 'exam_management/transport_fee_category_show'
 get 'exam_management/exam_fee_category_edit'
 get 'exam_management/exam_fee_category_update'
 get 'exam_management/delete_transport_fee_category'

 get 'exam_management/manage_exam_particulars'
 get 'exam_management/manage_exam_particulars_new'
 get 'exam_management/manage_exam_particulars_create'
  get 'exam_management/exam_edit_fee_particular'
  get 'exam_management/exam_update_fee_particular'
  get 'exam_management/exam_destroy_fee_particular'
 # get 'exam_management/delete_transport_fee_category'
  get 'exam_management/examination_fee_schedule'
 
  get 'exam_management/examination_delete_fee_schedule'
 
 get 'subject_specialization'=>'exam_management#subject_specialization',as: :subject_specialization
  get 'subject_specialization/new'=>'exam_management#new_subject_specialization',as: :new_subject_specialization
  get 'subject_specialization/:id/edit'=>'exam_management#edit_subject_specialization',as: :edit_subject_specialization
  post 'exam_management/create_subject_specialization'=>'exam_management#create_subject_specialization',as: :create_subject_specialization
  get 'exam_management/:id/show_subject_specialization'=>'exam_management#show_subject_specialization', as: :show_subject_specialization
  patch 'exam_management/:id/update_subject_specialization'=>'exam_management#update_subject_specialization', as: :update_subject_specialization
  get 'exam_management/:id/delete_subject_specialization'=>'exam_management#delete_subject_specialization', as: :delete_subject_specialization
  get 'subject_specialization_details'=>'exam_management#subject_specialization_details',as: :subject_specialization_details




  # get 'exam_management/exam_types'=>'exam_management#exam_types',as: :exam_types
  # get 'exam_management/exam_types/new'=>'exam_management#exam_types#new',as: :new_exam_types
  # get 'exam_management/exam_types/edit/:id'=>'exam_management#exam_types#edit',as: :edit_exam_types
 get 'exam_management/change_credential'
 get 'exam_management/student_details_excel_sheet'
 get 'exam_management/select_employee_for_specialization'
 

  get 'exam_management/show_hod_login_credentials'=>"exam_management#show_hod_login_credentials",as: :show_hod_login_credentials
  get 'exam_management/change_hod_login_password'=>"exam_management#change_hod_login_password",as: :change_hod_login_password

 get 'exam_management/unique_username'
 get 'exam_management/index_hod_login'
 get 'exam_management/new_hod_login'
 get 'exam_management/create_hod_login'
 get 'exam_management/edit_hod_login'=>"exam_management#edit_hod_login",as: :edit_hod_login
 get 'exam_management/update_hod_login'
 get 'exam_management/login_information'

get 'exam_management/show_hod_login/:id'=>"exam_management#show_hod_login",as: :show_hod_login
get 'exam_management/delete_hod_login/:id'=>"exam_management#delete_hod_login",as: :delete_hod_login
  get 'exam_management/store_manager_change_password'=>"exam_management#store_manager_change_password"#,as: :store_manager_change_password
  
 


 get 'exam_management/generate_exam_report'
 get 'exam_management/select_student_for_report'
 get 'exam_management/report_generation_for_student_data'
 get 'exam_management/generate_report_pdf'
 get 'exam_management/examination_details_for_course_evaluation'
 
 
 get 'exam_management/examination_marks_entry_for_subject_marks_evaluation'
 

 get 'exam_management/examination_details_for_subject'
  
  get 'exam_management/examination_details_for_course'
  get 'exam_management/examination_details_for_program'

  get 'exam_management/Examination_evaluation_data'
  get 'exam_management/examination_evaluation_create'
  get 'exam_management/exam_evaluation_data_edit/:id'=>'exam_management#exam_evaluation_data_edit', as: :exam_evaluation_data_edit
  get 'exam_management/exam_evaluation_data_show/:id'=>'exam_management#exam_evaluation_data_show', as: :exam_evaluation_data_show
  get 'exam_management/exam_evaluation_data_update'
  get 'exam_management/exam_evaluation_data_destroy'
  get 'exam_management/examination_marks_sheet_details'
  get 'exam_management/examination_marks_sheet_details_new'
  get 'exam_management/examination_marks_details_for_subject'
  get 'exam_management/examination_marks_entry_for_subject_marks'
  get 'exam_management/examination_marks_entry_create'
  get 'exam_management/examination_marks_sheet_details_show'=>'exam_management#examination_marks_sheet_details_show',as: :examination_marks_sheet_details_show
  get 'exam_management/examination_marks_sheet_details_edit'=>'exam_management#examination_marks_sheet_details_edit',as: :examination_marks_sheet_details_edit

get 'exam_management/issue_exam_application'

  get 'exam_management/issue_exam_application_new'
  get 'exam_management/issue_exam_application_show/:id'=>'exam_management#issue_exam_application_show', as: :issue_exam_application_show

  get 'exam_management/issue_exam_application_create'

  get 'exam_management/select_class_based_on_wing'
  get 'exam_management/select_students'

  get 'exam_management/select_students_edit'
  get 'exam_management/issue_exam_application_update'
  get 'exam_management/issue_exam_application_destroy'
  


  
  get 'exam_management/hall_ticket_pdf'=>'exam_management#hall_ticket_pdf', as: :hall_ticket_pdf
  get 'exam_management/exam_admit_card'=>'exam_management#exam_admit_card', as: :exam_admit_card
  get 'exam_management/mg_student_show'=>'exam_management#mg_student_show', as: :mg_student_show
  get 'exam_management/batch_wise_students'=>'exam_management#batch_wise_students', as: :batch_wise_students
  get 'exam_management/select_wing'=>'exam_management#select_wing', as: :select_wing
  get 'exam_management/exam_hall_ticket'=>'exam_management#exam_hall_ticket', as: :exam_hall_ticket
  
  get 'exam_management/program_category_data'

  get 'exam_management/program_category_data_new'
  get 'exam_management/program_category_create'
  get 'exam_management/program_category_edit'
  get 'exam_management/program_category_update'
  get 'exam_management/controller_examiner_show'
  get 'exam_management/assaign_exam_management_new'
  get 'exam_management/assaign_exam_controller_create'

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
	 layout "mindcom"
	   before_filter :login_required
	# helper_method :user_signed_in?

 #com
  #    before_filter :user_signed_in?

	 # def user_signed_in?
	 # 	# check user is logged in or not
	 # 	logger.info "Step -- 1"

	 # 	logger.info session[:user_id]
	 # 	logger.info "Step -- 2"
	 # end
	# layout false


	def index
	
		@batches = MgBatch.find_by(:mg_school_id=>session[:current_user_school_id],:is_deleted=>0)

		# logger.info " index page "+ @batches.name
	end

	def new
	@courses = MgCourse.new
	@grades=MgExamSystem.where(:is_enabled=>0).pluck(:grading_name,:grading_system)
	@schoolWing=MgWing.where(:is_deleted=>0,:mg_school_id=>session[:current_user_school_id]).pluck(:wing_name,:id)


    # render :layout => false
	end
	def course_by_admin
		@courses = MgCourse.new
		#render :layout => false
	end

	 def edit
	 	@schoolWing=MgWing.where(:is_deleted=>0,:mg_school_id=>session[:current_user_school_id]).pluck(:wing_name,:id)
	    @course = MgCourse.find(params[:id])
	    @grades=MgExamSystem.where(:is_enabled=>0).pluck(:grading_name,:grading_system)
	    @schoolWings=MgWing.where(:is_deleted=>0,:mg_school_id=>session[:current_user_school_id]).pluck(:wing_name,:id)
	     render :layout => false
	  end


	def create
		logger.info "Course Create Method"
	MgCourse.transaction do
	  	@course = MgCourse.new(course_params)

	   @batch = @course.mg_batches.build(batch_params)

	  	if @course.save
			
	    puts "Batch Saving data"
	    puts @batch.inspect
	  	 
	  	@timeformat=MgSchool.find_by_id(@batch.mg_school_id)

	    @startSaveDate = Date.strptime(params[:batch][:start_date],@timeformat.date_format)
		@endSaveDate = Date.strptime(params[:batch][:end_date],@timeformat.date_format)

		@batch.update(:start_date => @startSaveDate,:end_date => @endSaveDate)
	


	  		render 'index'
	  	else
	  		redirect_to 'new'
	  	end
	  end
	end

def check
	add_breadcrumb "modeltest-check", courses_check_path
end

def modeltest
	add_breadcrumb "modeltest", courses_modeltest_path
end

	def show
		
	end

	def addBatch
		logger.info "Batch will going to create"
	end

	def delete
		puts "inside delete"
		@course = MgCourse.find(params[:id])
			
   		 @course.is_deleted=1
   		  @course.save
   		  #Added By Bindhu
		batches_in_class=MgBatch.where(:mg_course_id=>params[:id])
		batches_in_class.each do |batch|
			batch.update(:is_deleted=>1)
		end

   	render 'index'
	end

	def grouped_batches

     @course = MgCourse.find(params[:id])
    @batch_groups = @course.mg_batch_groups
    @batches = @course.active_batches
    @batch_group = MgBatchGroup.new
	end	

	def create_batch_group
		@name=params[:batch_group]
		@batch_group = MgBatchGroup.new(:name=>@name)
		 
		
     @course = MgCourse.find(params[:course_id])
     @batch_group.mg_course_id = @course.id
     @error=false
    if params[:batch_ids].blank?
       @error=true
     end
     if @batch_group.valid? and @error==false
       @batch_group.save
       batches = params[:batch_ids]
       batches.each do|batch|
       MgGroupedBatch.create(:mg_batch_group_id=>@batch_group.id,:mg_batch_id=>batch)
      end
      
    else
      
     end
	end


	def update
		MgCourse.transaction do
		 @course = MgCourse.find(params[:id])
		
	      if @course.update(mg_course_params)
	      	logger.info " index page "
	      #	flash[:notice] = "Course updated successfully!"
	      	render 'index'

	      else
	       # render :layout => false
	      end
	    end
	end

  private

   def mg_course_params
    params.require(:course).permit(:course_name,:section_name,:code,:grading_type,:mg_wing_id)
  end
  
  def course_params

    params.require(:mg_course).permit(:course_name,:section_name,:code,:is_deleted,:grading_type,:mg_school_id,:mg_wing_id)

  end

  def batch_params
  	# date is not saving
     #params.require(:batch).permit( :name,:start_date,:end_date,:is_deleted,:mg_school_id)
     params.require(:batch).permit( :name,:is_deleted,:mg_school_id)
  end
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/views/classes/_batch.html.erb
<!-- Sec 2-->
      <h4><%= t('initial_batch') %></h4>
      
          <%= fields_for :batches do |batch_form| %>
            <label class="mg-label" for="name"><%= t('name') %></label>
                <div class="input-container">
                    <%= batch_form.text_field :name %>
                </div>

            <label class="mg-label" for="Start date"><%= t('Start date') %></label>
                <div class="input-container">
                    <%= batch_form.text_field :Start_date ,:class => 'Start_date' %>
                </div> 

             <label class="mg-label" for="End date"><%= t('End date') %></label>
                <div class="input-container">
                    <%= batch_form.text_field :End_date ,:id => 'End_date' %>
                </div>      
            </div>
          <% end %>

app/views/classes/_class_left.html.erb
<% navigation_add t('new'), :action=>'new' %>
<section id="userBodyContentBox" style="margin: 0 auto;">
    <table width=100% border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td valign="top" class="userBodyContentBox1">
                <aside class="userMenuBoxLeft">
                    <ul class="menuListHome">
                       <li class="myAccountMenu"><%=t('manage_class')%> </li> 

                           <li id="createDynamicLiID">
                                                    <a class="menuItemsActivities" href="/classes/index/" id="create_dynamic" >
                                                        <div class="setMenu"><i class="fa fa-list">&nbsp;&nbsp;</i><%=t('list_class_section')%><!-- <i class="fa fa-caret-left" style="color:#d5d8d9; position: absolute; right: 0px; transform: translateY(33%);"></i> -->
                                                        </div>
                                                    </a>
                                                </li>
                                           <!--  if user are able to create course -->
                                            <li id="createCourseTagLiID">
                                                <a class="menuItemsActivities" href="/classes/new/" id="createCourseIDgff">
                                                    <div class="setMenu"><i class="fa fa-book">&nbsp;&nbsp;</i><%=t('create_class')%><!-- <i class="fa fa-caret-left" style="color:#d5d8d9; position: absolute; right: 0px; transform: translateY(33%);"></i> -->
                                                    </div>
                                                </a>
                                            </li>
                  </ul>
                </aside>
            </td>
         
            <td id="recent_posts" class="mg-table-td-main-2">


                 

app/views/classes/_form.html.erb
<!-- Sec -->
  <div class="box">
    <h1>Edit Classes</h1>
    <%= form_for :course, url: classes_path(@course), method: :patch do |f| %>

       <label for="course_name"><%= t('class_name') %></label>
       <div class="input-container">
            <%= f.text_field :course_name %>
            </div>

       <label for="section_name"><%= t('section_name') %></label>
            <div class="input-container">
              <%= f.text_field :section_name %>
          </div>


          <label for="code"><%= t('code') %></label>
          <div class="input-container">
              <%= f.text_field :code %>
          </div>
			<br/>
           <%= f.submit "Submit" %>
   <% end %>
</div>

app/views/classes/addBatch.html.erb
<!-- Sec --><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores illo, rerum, quisquam fuga temporibus quos commodi ipsa tempore optio non sed hic quidem et esse sapiente itaque voluptate? Consequuntur, vel.</p>

app/views/classes/course_by_admin.html.erb
<!-- Sec --><div class="page-yield">

  <div class="box">
    <h4 class="mg-h4"><%= t('new_class') %></h4>
    <%= form_for @courses, :html=>{:id=>'new_course_form'}, url: {action: "create"} do |f| %>

       <label class="mg-label mg-custom-labels" for="course_name"><%= t('class_name') %></label>
       <div class="input-container">
            <%= f.text_field :course_name ,:class=>"mg-custom-labels"%>
            </div>

       <label class="mg-label mg-custom-labels" for="section_name"><%= t('section_name') %></label>
            <div class="input-container">
              <%= f.text_field :section_name ,:class=>"mg-custom-labels"%>
          </div>


          <label class="mg-label mg-custom-labels" for="code"><%= t('code') %></label>
          <div class="input-container">
              <%= f.text_field :code ,:class=>"mg-custom-labels"%>
          </div>
          <%= f.hidden_field :is_deleted, :value => 0 %> 
          <%= f.hidden_field :mg_school_id, :value => session[:current_user_school_id] %> 

          <!--Grading system will come here-->
          
          
          <h4 class="mg-h4"><%= t('initial_section') %></h4>
      
          <%= fields_for :batch do |batch_form| %>
           <%= batch_form.hidden_field :is_deleted, :value => 0 %> 
           <%= batch_form.hidden_field :mg_school_id, :value => session[:current_user_school_id] %> 
            <label class="mg-label mg-custom-labels" for="name"><%= t('name') %></label>
                <div class="input-container">
                    <%= batch_form.text_field :name ,:class=>"mg-custom-labels"%>
                </div>

            <label class="mg-label mg-custom-labels" for="Start date"><%= t('start_date') %></label>
                <div class="input-container">

                    <%= batch_form.text_field :start_date ,:class => 'Start_date mg-custom-labels' ,:id=>"Start_date"%>

                </div> 

             <label class="mg-label mg-custom-labels" for="End date"><%= t('end_date') %></label>
                <div class="input-container">
                    <%= batch_form.text_field :end_date ,:id => 'End_date' ,:class=>"mg-custom-labels"%>
                </div>      
          <% end %>
      <br/>
      <%= submit_tag t('save'), class: "submit" ,:class=>"mg-small-form-btn mg-custom-labels"%>
       
    <% end %>

    <div class="extender"></div>

  </div>
</div>
<br/>
<br/>
<script >
 

   $(document).ready(function(){
    

 dateFormatStr =  getJsDateFormat();

    
    $( "#End_date" ).datepicker({ changeMonth: true,
                changeYear: true, dateFormat: dateFormatStr });
    $( "#Start_date" ).datepicker({ changeMonth: true,
                changeYear: true, dateFormat: dateFormatStr });
    $( ".batch_start_date" ).datepicker({ changeMonth: true,
                changeYear: true, dateFormat: dateFormatStr });

    $("#new_course_form").validate({
      rules:{
        "mg_course[course_name]":{required:true},
     //   "mg_course[section_name]":{required:true},
        "mg_course[code]":{required:true},
        "batch[name]":{required:true},
        "batch[start_date]":{required:true},
        "batch[end_date]":{required:true},

      }
    });
  });



</script>




 

app/views/classes/create.html.erb
<!-- Sec --><h1>create</h1>

app/views/classes/dummy.html.erb
<!-- Sec --><h1>Generate New Course</h1>

<div id="page-yield">
	<div class="box">
		
		<%= form_for :courses, url: classes_path do |f| %>
			
			<label for="course_name">Course Name</label>
			<%= f.text_field :course_name %>

			<label for="section_name">Section Name</label>
			<%= f.text_field :section_name %>

			<label for="code">Code</label>
			<%= f.text_field :code %>

			<!--Grading system will come here-->

			<h4><%= t('initial_batch') %></h4>
			
		<% end %>

		<%= fields_for :batches do |batch_form| %>

		<label for="course_name">Course Name</label>
			<label for="name"><%= t('name') %></label>
                    <%= batch_form.text_field :name %>

                    <label for="Start date"><%= t('Start date') %></label>
                <div class="input-container">
                    <%= batch_form.text_field :Start_date ,:class => 'Start_date' %>
                </div> 

             <label for="End date"><%= t('End date') %></label>
                <div class="input-container">
                    <%= batch_form.text_field :End_date ,:id => 'End_date' %>
                </div>

		<% end %>

			<%= submit_tag t('save'), class: "submit" %>
	</div>
</div>


<script >
 

   $(function() {
          // $( ".Start_date" ).datepicker();
          dateFormatStr =  getJsDateFormat();
      
          $( "#End_date" ).datepicker(changeMonth: true,
                changeYear: true,dateFormat: dateFormatStr );

          $( ".Start_date" ).datepicker({
              beforeShow: function( input ) {
                  setTimeout(function() {
                      var headerPane = $( input )
                      .datepicker( "widget" )
                      .find( ".ui-datepicker-header" );

                      $( "<button>", {
                          text: "X",
                          click: function() {
                            $.datepicker.hide();
                          }
                      }).appendTo( headerPane );
                  }, 1 );
              },
              changeMonth: true,
                changeYear: true,
                dateFormat: dateFormatStr 
          });
        
      });


</script>
 

app/views/classes/edit.html.erb
<!-- Sec -->
<div class="box">
 <!--  <h1>Edit Courses</h1> -->
    <%= form_for :course, :html=>{:id=>'course_form'}, url: class_path(@course), method: :patch do |f| %>

      <label class="mg-label" for="course_name"><%=t('select_wing')%><span class="required-field"> *</label>  
      <div class="input-container">
      <%= f.select :mg_wing_id, options_for_select(@schoolWings,:selected=>@course.mg_wing_id),{:include_blank=>t('select')},:class=>"mg-select-btn"%>
      </div>
      
       <label class="mg-label " for="course_name"><%= t('class_name') %><span class="required-field"> *</span></label>
       <div class="input-container">
            <%= f.text_field :course_name ,:class=>"mg-text-field"%>
            </div>

      <!--  <label class="mg-label" for="section_name"><%#= t('section_name') %></label>
            <div class="input-container">
              <%#= f.text_field :section_name %>
          </div> -->


          <label class="mg-label" for="code"><%= t('code') %><span class="required-field"> *</span></label>
          <p class="input-container">
              <%= f.text_field :code ,:class=>"mg-text-field"%>
          </p>
			<p>
           <%#= f.submit  "Submit" ,:class=>"mg-small-form-btn"%>
           <a onclick="$(this).closest('form').submit()" class="mg-small-form-btn"><%=t("save")%></a>
           <%= link_to t('cancel'), :back, {:class=>"mg-small-form-btn cancel-form-dialog"} %>
      </p>
  <% end %>
</div>


<!-- <button class="cancel-form-dialog"><%#= t('cancel') %></button> -->
<script>
  $(document).ready(function(){
    $("#course_form").validate({
      rules:{
        "course[mg_wing_id]":{required:true},
        "course[course_name]":{required:true},
      //  "course[section_name]":{required:true},
        "course[code]":{required:true}

      }
    });
  });
</script>

app/views/classes/grouped_batches.html.erb
 
  <h3>Grouped Batches</h3>
 
</div>
<div id="page-yield">

  

  
  
    <%=form_for :batch_group,:url=>{:action=>"create_batch_group", :course_id=>@course.id} do |f| %>

      <div id="form-content">
        <div class="label-field-pair">
          <label for="name">Name</label>
          <div class="text-input-bg"><%= f.text_field :name %></div>
        </div>
        <div class="grades">
        <div class="label-field-pair">
          <label for="configuration_grading_systems">Select Batches :</label>
        </div>
        <div class="fee_category_scroll">
          <% @batches.each do |b| %>
         
            <div class="each_batch">
              <%= check_box_tag "batch_ids[]", b.id,false,:class=>'batches_box' %> <%= b.name %>
            </div>
          <% end %>
        </div>
      </div>

        <div class="extender"></div>

        <div id="submit-button">
          <%=f.submit "submit" %>
        </div>


      </div>
    <% end %>
  </div>
  <div id="category-list">
    <%#= render :partial=>"batch_groups" %>
  </div>

</div>

app/views/classes/update.js.erb
// $('#people_table').append("<%= j render partial: 'table_row', locals: {person: @person } %>");
$(this).update_course_success();